### PR TITLE
Refactor; Implement DWWC; Split degree_weight and diffusion modules

### PR DESCRIPTION
**Pull request by dhimmel**
Closes https://github.com/greenelab/hetmech/pull/25
Closes https://github.com/greenelab/hetmech/pull/26

@kkloste, now cypher and matrix implementations of DWWC agree!

### CODE REVIEW

**Comment by dhimmel** [comment]
In https://github.com/greenelab/hetmech/pull/28/commits/d0854cc8a019aae7e3d70b0f23a1120ea457ea4f, we now have three DWWC implementations agreeing with each other!

**Comment by kkloste** [comment]
That's wonderful!
Is there anything in this PR I should look at, or can we merge and squash?

**Comment by dhimmel** [comment]
@kkloste you should approve if it looks good to you. I'll take care of the merge... I may interactively rebase a bit.

**Comment by dhimmel** [comment]
@kkloste I rebased to try to combine the commits into meaninful groups. Now down to 3 commits. Not perfect, but good enough. Will do a merge commit to preserve these 3 commits.

**Pull request merged**
