### PR TITLE
Analyzed Compounds with Divergent Predictions

### PR DESCRIPTION
**Pull request by ben-heil**
This notebook looks at the compounds that have a high unsupervised ranking and low supervised ranking and vice versa. The comparison is done by pulling out the top and bottom 500 entries of the dataframe sorted by difference between supervised and unsupervised ranking and summing up the negative log p_values of each metapath.

It is interesting that the metapaths that are ranking highly in Rephetio over Hetmech are metapaths that make intuitive sense as disease treatment pathways, like CbGaD or CbGbCtD.

Also, sorry that the bars aren't sorted by p_value, I couldn't figure out how to get it to work.

image

### CODE REVIEW

**Comment by dhimmel** [comment]
Let's go over these plots in person. However, I'm having trouble taking away too much information. Can you, in the notebook, show the metapaths contributing to each of the top 3 unsupervised predictions that were ranked poorly by Rephetio? I think this could be a case where looking at the raw-ish data is enough to get a good idea of what is going on.

**Comment by ben-heil** [comment]
Screenshot from 2019-03-13 09-21-02

**Comment by ben-heil** [comment]
Here are the top ten ranked paths from deslanoside, acetyldigitoxin, and betamethasone:
Screenshot from 2019-03-14 17-50-25

**Comment by ben-heil** [comment]
I'll look at the biological implications of these paths tomorrow morning

**Comment by ben-heil** [comment]
In order of occurence in the chart:

**Paths because epilepsy resembles migraines:**
- Progesterone has been found to be associated with a decrease in [seizure duration and frequency in rats](https://www.sciencedirect.com/science/article/pii/S0306453099000682). PGR is the gene that encodes for progesterone receptors.
- ATP1A2 is a gene typically found mutated in people with familial migraines, but has also been found to be [associated with epilepsy](https://www.ncbi.nlm.nih.gov/pubmed/18028407)
- Some ATP1A3 mutations have been [associated with early life epilepsy](https://www.ncbi.nlm.nih.gov/pubmed/25656163)
- Prednisone has both been used as a treatment for epilepsy in [this case study](https://www.ncbi.nlm.nih.gov/pubmed/12770672), and can exacerbate epileptic seizures [by way of hypocalcemia](https://www.epilepsy.com/learn/professionals/resource-library/tables/drugs-may-lower-seizure-threshold)

**Other paths**
- It is unclear to me whether WARS truly has an association with epilepsy, [Genecards/Malacards list it](https://www.malacards.org/card/reflex_epilepsy), but they cite [this database](https://diseases.jensenlab.org/Entity?documents=10&type1=9606&id1=ENSP00000347495&type2=-26&id2=DOID:2548). I think that the associations are inferred because Wistar Audiogenic Rats (WARs) are a model of epilepsy and WARS is a human gene.
- Betamethasone treats lupus, which is palliated by Pregabalin which is a known epilepsy drug
- OatP2, another name for SLCO1A2 has been [found to be downregulated in rats with chronic epilepsy](https://www.tandfonline.com/doi/abs/10.1179/174313209X408954). This association feels a lot weaker than the others, it took some digging to find any connection at all.

**Top Three Compounds**
- Corticosteroids are sometimes used to treat epilepsy, and betamethasone is a corticosteroid. Though prednisone seems to be the most common treatment, betamethasone has been used to treat epilepsy in at least [one case study](https://www.sciencedirect.com/science/article/pii/S2213323216300172)
- Both deslanoside and acetyldigitoxin(technically digitoxin/digoxin, acetyldigitoxin is a derivative) are used to increase heart contractility by targeting sodium/potassium pumps. I imagine that increasing contractility means that these drugs would have the opposite of the intended effect if used to treat epilepsy(https://www.drugbank.ca/drugs/DB01078, https://www.drugbank.ca/drugs/DB00390)

**Comment by dhimmel** [comment]
Great analysis and investigation. My only request would be to split the table with actual paths for deslanoside, acetyldigitoxin, and betamethasone into three tables (or one table, with the top-level sort being compound). It's a bit challenging to browse through the table when the paths for different endpoints are intermixed.

**Comment by dhimmel** [comment]
There is still an issue with https://github.com/greenelab/hetmech/pull/160/commits/3cdd6266fb2340a4bd434342c2f3f8fa6a9fcb16. We should show the top 10 paths per compound, not the top 10 paths across the 3 compounds.

**Comment by ben-heil** [comment]
Ahh I see, I guess I didn't understand what you were asking for. I'll go fix it

**Comment by dhimmel** [comment]
# Browser links

## Betamethasone

https://neo4j.het.io/browser/?cmd=play&arg=https://neo4j.het.io/guides/rep/DB00443/DOID_1826.html

> Project Rephetio predicted a probability of 0.097% that Betamethasone (DB00443) treats epilepsy syndrome (DOID:1826). This probability represents a -0.73-fold enrichment over the background prevalence of treatment. This prediction is in the 66.2th percentile for Betamethasone and the 5.5th percentile for epilepsy syndrome.

Unsupervised rank 100

https://het.io/search/?source=10098&target=6215

## Acetyldigitoxin

https://neo4j.het.io/browser/?cmd=play&arg=https://neo4j.het.io/guides/rep/DB00511/DOID_1826.html

> Project Rephetio predicted a probability of 0.064% that Acetyldigitoxin (DB00511) treats epilepsy syndrome (DOID:1826). This probability represents a -0.82-fold enrichment over the background prevalence of treatment. This prediction is in the 24.3th percentile for Acetyldigitoxin and the 1.2th percentile for epilepsy syndrome.

Unsupervised rank 275

https://het.io/search/?source=45131&target=6215

## Deslanoside

https://neo4j.het.io/browser/?cmd=play&arg=https://neo4j.het.io/guides/rep/DB01078/DOID_1826.html

> Project Rephetio predicted a probability of 0.064% that Deslanoside (DB01078) treats epilepsy syndrome (DOID:1826). This probability represents a -0.82-fold enrichment over the background prevalence of treatment. This prediction is in the 24.3th percentile for Deslanoside and the 1.2th percentile for epilepsy syndrome.

Unsupervised rank 276

https://het.io/search/?source=641&target=6215

**Comment by dhimmel** [comment]
## Betamethasone literature

 **Prenatal betamethasone exposure increases corticotropin-releasing hormone expression along with increased hippocampal slice excitability in the developing hippocampus**   
Melissa J Benson, Marcela Lauková, Karin Borges, Jana Velíšková, Libor Velíšek  
*Epilepsy Research* (2020-02) <https://doi.org/gg5c8z>   
DOI: [10.1016/j.eplepsyres.2020.106276](https://doi.org/10.1016/j.eplepsyres.2020.106276) · PMID: [31954921](https://www.ncbi.nlm.nih.gov/pubmed/31954921)

> our study shows that prenatal betamethasone-exposure alters hippocampal circuitry resulting in an increased response to epileptogenic stimuli in immature brain. We present evidence that altered hippocampal CRH levels as well as limited changes in CRH receptor type sensitivity may contribute to this proconvulsant effect in the hippocampus.

**Altered expression of KCC2 in GABAergic interneuron contributes prenatal stress-induced epileptic spasms in infant rat**   
Hyunjung Baek, Min-Hee Yi, Sudip Pandit, Jin Bong Park, Hyeok Hee Kwon, Enji Zhang, Sena Kim, Nara Shin, Eunjee Kim, Young Ho Lee, … Joon Won Kang  
*Neurochemistry International* (2016-07) <https://doi.org/f8vfdv>   
DOI: [10.1016/j.neuint.2016.05.006](https://doi.org/10.1016/j.neuint.2016.05.006) · PMID: [27180051](https://www.ncbi.nlm.nih.gov/pubmed/27180051)

> Taken together, our results showed that prenatal stress with betamethasone or AIS altered the maturation of GABAergic progenitors and resulted in the lack of GABA input, which in turn, decreased KCC2 expression and lowered seizure threshold.

**Pull request merged**
